using System.Diagnostics.CodeAnalysis;
using X10D.Generator.FileRegenerator;

namespace X10D.Generator;

public static class Program
{
    public const string AutoGeneratedString1 = "This class is auto generated and will be overridden if any changes are made.";
    public const string AutoGeneratedString2 = "To make edits to this class edit the X10D.Generator project.";

    public const string CustomPath = "../../../../X10D.Performant/src/Custom";

    [SuppressMessage("ReSharper", "UnusedVariable")]
    public static void Main()
    {
        EquatableGenerator equatable = new();
        EquatableDocumentationGenerator documentationGenerator = new();
        Regenerator regenerator = new();
        regenerator.RegenerateSingleExtensions();
        regenerator.RegenerateIntegerExtensions();
    }
}