using System.Diagnostics.CodeAnalysis;
using X10D.Generator.FileRegenerator;

namespace X10D.Generator
{
    public static class Program
    {
        public const string AutoGeneratedString = @"// This class is auto generated and will be overridden if any changes are made.
// To make edits to this class edit the X10D.Generator project.

";

        public const string CustomPath = "../../../../X10D.Performant/src/Custom";

        [SuppressMessage("ReSharper", "UnusedVariable")]
        public static void Main()
        {
            EquatableBuilder equatable = new();
            EquatableDocumentationBuilder documentationBuilder = new();
            Regenerator regenerator = new();
        }
    }
}