using X10D.Generator.EquatableExtensionsBuilder;

namespace X10D.Generator
{
    public static class Program
    {
        public const string AutoGeneratedString = @"// This class is auto generated and will be overridden if any changes are made.
// To make edits to this class edit the X10D.Generator project.

";

        public static void Main()
        {
            EquatableBuilder equatable = new();
        }
    }
}