using System.Text;

namespace X10D.Generator;

public partial class EquatableDocumentationGenerator
{
    public EquatableDocumentationGenerator()
    {
        StringBuilder xmlBuilder = new();

        xmlBuilder.AppendLine("<!--");
        xmlBuilder.AppendLine(Program.AutoGeneratedString1);
        xmlBuilder.AppendLine(Program.AutoGeneratedString2);
        xmlBuilder.AppendLine("-->");

        xmlBuilder.AppendLine(@"<members>");
        xmlBuilder.Append(BuildMethodCluster(16, BuildAndMethod));
        xmlBuilder.Append(BuildMethodCluster(16, BuildNAndMethod));
        xmlBuilder.Append(BuildMethodCluster(16, BuildNOrMethod));
        xmlBuilder.Append(BuildMethodCluster(16, BuildOrMethod));
        xmlBuilder.Append(BuildMethodCluster(16, BuildXNOrMethod));
        xmlBuilder.Append(BuildMethodCluster(16, BuildXOrMethod));
        xmlBuilder.AppendLine(@"</members>");

        File.WriteAllText(Path.Combine(Program.CustomPath, "IEquatableExtensions", "EquatableExtensions.g.xml"), xmlBuilder.ToString());
    }
}