name: .NET Core

on: [push, pull_request]

env:
  DOTNET_VERSION: '5.0.x'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ 'win-x64', 'linux-x64', 'osx-x64' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build ${{ matrix.runtime }}
        run: dotnet publish -r ${{ matrix.runtime }} -c Release /p:GeneratePackageOnBuild=false
      - name: Artifact Upload ${{ matrix.runtime }}
        uses: actions/upload-artifact@v2
        with:
          name: X10D.Performant-${{ matrix.runtime }}
          path: X10D.Performant/bin/Release/net5.0/${{ matrix.runtime }}/publish/X10D.Performant.dll

  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
